name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  tron:
    path: ../
  grpc: ^3.1.0
  hex: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
