name: tron
description: Dart API Library for interacting with the TRON Network through gRPC and Rest APIs.
version: 0.0.3
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_tron/

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  fixnum: ^1.1.1
  protobuf_google: ^1.0.0
  protobuf: ^4.0.0
  grpc: ^4.0.4

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
